export const AUTH = {
  SET_AUTH: "SET_AUTH",
  SET_AUTH_SUCCESS: "SET_AUTH_SUCCESS",
  SET_AUTH_FAILED: "SET_AUTH_FAILED",
};

export const USERS = {
  GET_USERS: "GET_USERS",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILED: "GET_USERS_FAILED",
  SET_USERS: "SET_USERS",
  SET_USERS_SUCCESS: "SET_USERS_SUCCESS",
  SET_USERS_FAILED: "SET_USERS_FAILED",
};

export const ROLLCALL = {
  GET_VERIFY: "GET_VERIFY",
  GET_VERIFY_SUCCESS: "GET_VERIFY_SUCCESS",
  GET_VERIFY_FAILED: "GET_VERIFY_FAILED",
};
